### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by stevedanomodolor** [ros-planning/navigation2#4264]
## Bug report

**Required Info:**

- Operating System:
  - ubunut 22 
- ROS2 Version:
  - ros rolling docker
- Version or commit hash:
  - current main
- DDS implementation:
  - default 

#### Steps to reproduce issue

```
export $ROS_DISTRO=rolling
docker build --tag navigation2:$ROS_DISTRO \ 
  --build-arg FROM_IMAGE=ros:$ROS_DISTRO \
  --build-arg OVERLAY_MIXINS="release ccache lld" \
  --cache-from ghcr.io/ros-planning/navigation2:main \
  ./navigation2

```

#### Expected behavior
It should build
#### Actual behavior
It does not build and it gives and error 
```
 [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 6.63kB                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ros:rolling                                                                                                                           0.8s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 229B                                                                                                                                                        0.0s
 => importing cache manifest from ghcr.io/ros-planning/navigation2:main                                                                                                                  1.3s
 => => inferred cache manifest type: application/vnd.docker.distribution.manifest.v2+json                                                                                                0.0s
 => CACHED [builder  1/11] FROM docker.io/library/ros:rolling@sha256:831fa3f0bb3667c510d945bccfa86847f67d807aaae74342a61bc3a983719f48                                                    0.0s
 => [internal] load build context                                                                                                                                                        0.9s
 => => transferring context: 126.19MB                                                                                                                                                    0.9s
 => [builder  2/11] RUN echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";\n' > /etc/apt/apt.conf.d/01norecommend                                                            0.3s
 => ERROR [builder  3/11] RUN apt-get update &&     apt-get upgrade -y --with-new-pkgs &&     apt-get install -y       ccache       lcov       lld       python3-pip       ros-rolling  76.3s
 => CACHED [cacher 2/8] WORKDIR /opt/underlay_ws/src                                                                                                                                     0.0s
 => CACHED [cacher 3/8] COPY ./tools/underlay.repos ../                                                                                                                                  0.0s
 => [cacher 4/8] RUN vcs import ./ < ../underlay.repos                                                                                                                                   0.5s
 => [cacher 5/8] WORKDIR /opt/overlay_ws/src                                                                                                                                             0.0s
 => [cacher 6/8] COPY ./ ./navigation2                                                                                                                                                   0.3s
 => [cacher 7/8] WORKDIR /opt                                                                                                                                                            0.0s
 => [cacher 8/8] RUN find . -name "src" -type d       -mindepth 1 -maxdepth 2 -printf '%P\n'       | xargs -I % mkdir -p /tmp/opt/% &&     find . -name "package.xml"       | xargs cp   0.5s
------                                                                                                                                                                                        
 > [builder  3/11] RUN apt-get update &&     apt-get upgrade -y --with-new-pkgs &&     apt-get install -y       ccache       lcov       lld       python3-pip       ros-rolling-rmw-fastrtps-cpp       ros-rolling-rmw-connextdds       ros-rolling-rmw-cyclonedds-cpp     && pip3 install       fastcov       git+https://github.com/ruffsl/colcon-cache.git@a937541bfc496c7a267db7ee9d6cceca61e470ca       git+https://github.com/ruffsl/colcon-clean.git@a7f1074d1ebc1a54a6508625b117974f2672f2a9     && rosdep update     && colcon mixin update     && colcon metadata update     && rm -rf /var/lib/apt/lists/*:                                                                                                                                                                  
0.604 Get:1 http://archive.ubuntu.com/ubuntu noble InRelease [255 kB]                                                                                                                         
0.606 Get:2 http://security.ubuntu.com/ubuntu noble-security InRelease [90.7 kB]                                                                                                              
1.057 Get:3 http://packages.ros.org/ros2/ubuntu noble InRelease [4658 B]                                                                                                                      
1.158 Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [89.7 kB]
1.284 Get:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease [90.8 kB]
1.334 Get:6 http://packages.ros.org/ros2/ubuntu noble/main amd64 Packages [344 kB]
1.412 Get:7 http://archive.ubuntu.com/ubuntu noble/restricted amd64 Packages [138 kB]
1.461 Get:8 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1806 kB]
1.745 Get:9 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.4 MB]
3.019 Get:10 http://archive.ubuntu.com/ubuntu noble/multiverse amd64 Packages [295 kB]
3.811 Fetched 22.6 MB in 3s (6575 kB/s)
3.811 Reading package lists...
4.405 Reading package lists...
5.281 Building dependency tree...
5.489 Reading state information...
5.560 Calculating upgrade...
5.855 The following packages will be upgraded:
5.856   bash bzip2 diffutils findutils hostname libacl1 libassuan0 libattr1
5.856   libbz2-1.0 libdatrie1 libdeflate0 libffi8 libgcrypt20 libgpg-error0
5.856   libgraphite2-3 libice6 libisl23 liblerc4 libpython3-dev libpython3-stdlib
5.856   libpython3.12-dev libpython3.12-minimal libpython3.12-stdlib
5.857   libpython3.12t64 python3 python3-dev python3-minimal python3-psutil
5.858   python3.12 python3.12-dev python3.12-minimal
6.221 31 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
6.221 Need to get 17.8 MB of archives.
6.221 After this operation, 199 kB disk space will be freed.
6.221 Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 bash amd64 5.2.21-2ubuntu4 [794 kB]
7.189 Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 diffutils amd64 1:3.10-1build1 [177 kB]
7.191 Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 findutils amd64 4.9.0-5build1 [298 kB]
7.196 Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 hostname amd64 3.23+nmu2ubuntu2 [11.1 kB]
7.197 Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 python3.12-dev amd64 3.12.3-1 [498 kB]
7.408 Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 python3.12 amd64 3.12.3-1 [651 kB]
7.417 Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3.12-dev amd64 3.12.3-1 [5671 kB]
7.842 Get:8 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3.12t64 amd64 3.12.3-1 [2339 kB]
7.977 Get:9 http://archive.ubuntu.com/ubuntu noble/main amd64 bzip2 amd64 1.0.8-5.1 [34.5 kB]
7.978 Get:10 http://archive.ubuntu.com/ubuntu noble/main amd64 libbz2-1.0 amd64 1.0.8-5.1 [34.3 kB]
7.980 Get:11 http://archive.ubuntu.com/ubuntu noble/main amd64 libffi8 amd64 3.4.6-1build1 [24.7 kB]
7.981 Get:12 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3.12-stdlib amd64 3.12.3-1 [2067 kB]
8.153 Get:13 http://archive.ubuntu.com/ubuntu noble/main amd64 python3.12-minimal amd64 3.12.3-1 [2343 kB]
8.315 Get:14 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3.12-minimal amd64 3.12.3-1 [833 kB]
8.370 Get:15 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3-dev amd64 3.12.3-0ubuntu1 [10.2 kB]
8.371 Get:16 http://archive.ubuntu.com/ubuntu noble/main amd64 python3-dev amd64 3.12.3-0ubuntu1 [26.7 kB]
8.372 Get:17 http://archive.ubuntu.com/ubuntu noble/main amd64 python3-minimal amd64 3.12.3-0ubuntu1 [27.2 kB]
8.374 Get:18 http://archive.ubuntu.com/ubuntu noble/main amd64 python3 amd64 3.12.3-0ubuntu1 [24.1 kB]
8.375 Get:19 http://archive.ubuntu.com/ubuntu noble/main amd64 libpython3-stdlib amd64 3.12.3-0ubuntu1 [9890 B]
8.377 Get:20 http://archive.ubuntu.com/ubuntu noble/main amd64 libacl1 amd64 2.3.2-1build1 [16.8 kB]
8.377 Get:21 http://archive.ubuntu.com/ubuntu noble/main amd64 libattr1 amd64 1:2.5.2-1build1 [11.3 kB]
8.379 Get:22 http://archive.ubuntu.com/ubuntu noble/main amd64 libgpg-error0 amd64 1.47-3build2 [70.0 kB]
8.423 Get:23 http://archive.ubuntu.com/ubuntu noble/main amd64 libgcrypt20 amd64 1.10.3-2build1 [532 kB]
8.529 Get:24 http://archive.ubuntu.com/ubuntu noble/main amd64 libassuan0 amd64 2.5.6-1build1 [37.3 kB]
8.532 Get:25 http://archive.ubuntu.com/ubuntu noble/main amd64 libdatrie1 amd64 0.2.13-3build1 [19.0 kB]
8.533 Get:26 http://archive.ubuntu.com/ubuntu noble/main amd64 libdeflate0 amd64 1.19-1build1 [43.8 kB]
8.535 Get:27 http://archive.ubuntu.com/ubuntu noble/main amd64 libgraphite2-3 amd64 1.3.14-2build1 [73.0 kB]
8.541 Get:28 http://archive.ubuntu.com/ubuntu noble/main amd64 libice6 amd64 2:1.0.10-1build3 [41.4 kB]
8.544 Get:29 http://archive.ubuntu.com/ubuntu noble/main amd64 libisl23 amd64 0.26-3build1 [680 kB]
8.589 Get:30 http://archive.ubuntu.com/ubuntu noble/main amd64 liblerc4 amd64 4.0.0+ds-4ubuntu2 [179 kB]
8.601 Get:31 http://archive.ubuntu.com/ubuntu noble/main amd64 python3-psutil amd64 5.9.8-2build2 [195 kB]
8.747 debconf: delaying package configuration, since apt-utils is not installed
8.773 Fetched 17.8 MB in 3s (6482 kB/s)
(Reading database ... 39192 files and directories currently installed.)
8.812 Preparing to unpack .../bash_5.2.21-2ubuntu4_amd64.deb ...
8.820 Unpacking bash (5.2.21-2ubuntu4) over (5.2.21-2ubuntu2) ...
8.869 Setting up bash (5.2.21-2ubuntu4) ...
8.879 update-alternatives: error: alternative path /usr/share/man/man7/bash-builtins.7.gz doesn't exist
(Reading database ... 39192 files and directories currently installed.)
8.921 Preparing to unpack .../diffutils_1%3a3.10-1build1_amd64.deb ...
8.925 Unpacking diffutils (1:3.10-1build1) over (1:3.10-1) ...
8.957 Setting up diffutils (1:3.10-1build1) ...
(Reading database ... 39192 files and directories currently installed.)
8.998 Preparing to unpack .../findutils_4.9.0-5build1_amd64.deb ...
9.002 Unpacking findutils (4.9.0-5build1) over (4.9.0-5) ...
9.051 Setting up findutils (4.9.0-5build1) ...
(Reading database ... 39191 files and directories currently installed.)
9.097 Preparing to unpack .../hostname_3.23+nmu2ubuntu2_amd64.deb ...
9.102 Unpacking hostname (3.23+nmu2ubuntu2) over (3.23+nmu2ubuntu1) ...
9.130 Setting up hostname (3.23+nmu2ubuntu2) ...
(Reading database ... 39191 files and directories currently installed.)
9.173 Preparing to unpack .../0-python3.12-dev_3.12.3-1_amd64.deb ...
9.177 Unpacking python3.12-dev (3.12.3-1) over (3.12.2-5ubuntu3) ...
9.202 Preparing to unpack .../1-python3.12_3.12.3-1_amd64.deb ...
9.253 Unpacking python3.12 (3.12.3-1) over (3.12.2-5ubuntu3) ...
9.281 Preparing to unpack .../2-libpython3.12-dev_3.12.3-1_amd64.deb ...
9.286 Unpacking libpython3.12-dev:amd64 (3.12.3-1) over (3.12.2-5ubuntu3) ...
9.680 Preparing to unpack .../3-libpython3.12t64_3.12.3-1_amd64.deb ...
9.689 Unpacking libpython3.12t64:amd64 (3.12.3-1) over (3.12.2-5ubuntu3) ...
9.771 Preparing to unpack .../4-bzip2_1.0.8-5.1_amd64.deb ...
9.778 Unpacking bzip2 (1.0.8-5.1) over (1.0.8-5ubuntu1) ...
9.816 Preparing to unpack .../5-libbz2-1.0_1.0.8-5.1_amd64.deb ...
9.824 Unpacking libbz2-1.0:amd64 (1.0.8-5.1) over (1.0.8-5ubuntu1) ...
9.859 Setting up libbz2-1.0:amd64 (1.0.8-5.1) ...
(Reading database ... 39191 files and directories currently installed.)
9.908 Preparing to unpack .../libffi8_3.4.6-1build1_amd64.deb ...
9.914 Unpacking libffi8:amd64 (3.4.6-1build1) over (3.4.6-1) ...
9.951 Setting up libffi8:amd64 (3.4.6-1build1) ...
(Reading database ... 39191 files and directories currently installed.)
9.994 Preparing to unpack .../libpython3.12-stdlib_3.12.3-1_amd64.deb ...
10.03 Unpacking libpython3.12-stdlib:amd64 (3.12.3-1) over (3.12.2-5ubuntu3) ...
10.38 Preparing to unpack .../python3.12-minimal_3.12.3-1_amd64.deb ...
10.39 Unpacking python3.12-minimal (3.12.3-1) over (3.12.2-5ubuntu3) ...
10.47 Preparing to unpack .../libpython3.12-minimal_3.12.3-1_amd64.deb ...
10.52 Unpacking libpython3.12-minimal:amd64 (3.12.3-1) over (3.12.2-5ubuntu3) ...
10.76 Preparing to unpack .../libpython3-dev_3.12.3-0ubuntu1_amd64.deb ...
10.77 Unpacking libpython3-dev:amd64 (3.12.3-0ubuntu1) over (3.12.2-0ubuntu2) ...
10.79 Preparing to unpack .../python3-dev_3.12.3-0ubuntu1_amd64.deb ...
10.79 Unpacking python3-dev (3.12.3-0ubuntu1) over (3.12.2-0ubuntu2) ...
10.82 Setting up libpython3.12-minimal:amd64 (3.12.3-1) ...
10.83 Setting up python3.12-minimal (3.12.3-1) ...
(Reading database ... 39191 files and directories currently installed.)
11.59 Preparing to unpack .../python3-minimal_3.12.3-0ubuntu1_amd64.deb ...
11.60 Unpacking python3-minimal (3.12.3-0ubuntu1) over (3.12.2-0ubuntu2) ...
11.64 Setting up python3-minimal (3.12.3-0ubuntu1) ...
(Reading database ... 39191 files and directories currently installed.)
11.79 Preparing to unpack .../python3_3.12.3-0ubuntu1_amd64.deb ...
11.85 Unpacking python3 (3.12.3-0ubuntu1) over (3.12.2-0ubuntu2) ...
11.87 Preparing to unpack .../libpython3-stdlib_3.12.3-0ubuntu1_amd64.deb ...
11.88 Unpacking libpython3-stdlib:amd64 (3.12.3-0ubuntu1) over (3.12.2-0ubuntu2) ...
11.90 Preparing to unpack .../libacl1_2.3.2-1build1_amd64.deb ...
11.90 Unpacking libacl1:amd64 (2.3.2-1build1) over (2.3.2-1) ...
11.93 Setting up libacl1:amd64 (2.3.2-1build1) ...
(Reading database ... 39191 files and directories currently installed.)
11.98 Preparing to unpack .../libattr1_1%3a2.5.2-1build1_amd64.deb ...
11.98 Unpacking libattr1:amd64 (1:2.5.2-1build1) over (1:2.5.2-1) ...
12.01 Setting up libattr1:amd64 (1:2.5.2-1build1) ...
(Reading database ... 39191 files and directories currently installed.)
12.06 Preparing to unpack .../libgpg-error0_1.47-3build2_amd64.deb ...
12.06 Unpacking libgpg-error0:amd64 (1.47-3build2) over (1.47-3build1) ...
12.09 Setting up libgpg-error0:amd64 (1.47-3build2) ...
(Reading database ... 39191 files and directories currently installed.)
12.14 Preparing to unpack .../libgcrypt20_1.10.3-2build1_amd64.deb ...
12.14 Unpacking libgcrypt20:amd64 (1.10.3-2build1) over (1.10.3-2) ...
12.17 Setting up libgcrypt20:amd64 (1.10.3-2build1) ...
(Reading database ... 39191 files and directories currently installed.)
12.22 Preparing to unpack .../libassuan0_2.5.6-1build1_amd64.deb ...
12.22 Unpacking libassuan0:amd64 (2.5.6-1build1) over (2.5.6-1) ...
12.25 Setting up libassuan0:amd64 (2.5.6-1build1) ...
(Reading database ... 39191 files and directories currently installed.)
12.31 Preparing to unpack .../0-libdatrie1_0.2.13-3build1_amd64.deb ...
12.31 Unpacking libdatrie1:amd64 (0.2.13-3build1) over (0.2.13-3) ...
12.34 Preparing to unpack .../1-libdeflate0_1.19-1build1_amd64.deb ...
12.34 Unpacking libdeflate0:amd64 (1.19-1build1) over (1.19-1) ...
12.37 Preparing to unpack .../2-libgraphite2-3_1.3.14-2build1_amd64.deb ...
12.38 Unpacking libgraphite2-3:amd64 (1.3.14-2build1) over (1.3.14-2) ...
12.40 Preparing to unpack .../3-libice6_2%3a1.0.10-1build3_amd64.deb ...
12.41 Unpacking libice6:amd64 (2:1.0.10-1build3) over (2:1.0.10-1build2) ...
12.44 Preparing to unpack .../4-libisl23_0.26-3build1_amd64.deb ...
12.44 Unpacking libisl23:amd64 (0.26-3build1) over (0.26-3) ...
12.48 Preparing to unpack .../5-liblerc4_4.0.0+ds-4ubuntu2_amd64.deb ...
12.49 Unpacking liblerc4:amd64 (4.0.0+ds-4ubuntu2) over (4.0.0+ds-4ubuntu1) ...
12.51 Preparing to unpack .../6-python3-psutil_5.9.8-2build2_amd64.deb ...
12.58 Unpacking python3-psutil (5.9.8-2build2) over (5.9.8-2build1) ...
12.64 Setting up libgraphite2-3:amd64 (1.3.14-2build1) ...
12.65 Setting up libice6:amd64 (2:1.0.10-1build3) ...
12.65 Setting up liblerc4:amd64 (4.0.0+ds-4ubuntu2) ...
12.66 Setting up libpython3.12-stdlib:amd64 (3.12.3-1) ...
12.66 Setting up libdatrie1:amd64 (0.2.13-3build1) ...
12.66 Setting up python3.12 (3.12.3-1) ...
13.47 Setting up libdeflate0:amd64 (1.19-1build1) ...
13.47 Setting up bzip2 (1.0.8-5.1) ...
13.47 Setting up libpython3.12t64:amd64 (3.12.3-1) ...
13.48 Setting up libisl23:amd64 (0.26-3build1) ...
13.48 Setting up libpython3-stdlib:amd64 (3.12.3-0ubuntu1) ...
13.49 Setting up python3 (3.12.3-0ubuntu1) ...
13.57 Setting up libpython3.12-dev:amd64 (3.12.3-1) ...
13.57 Setting up python3-psutil (5.9.8-2build2) ...
13.89 Setting up python3.12-dev (3.12.3-1) ...
13.89 Setting up libpython3-dev:amd64 (3.12.3-0ubuntu1) ...
13.90 Setting up python3-dev (3.12.3-0ubuntu1) ...
13.90 Processing triggers for libc-bin (2.39-0ubuntu8) ...
13.92 Processing triggers for debianutils (5.17build1) ...
13.97 Reading package lists...
14.55 Building dependency tree...
14.68 Reading state information...
14.85 ros-rolling-rmw-fastrtps-cpp is already the newest version (8.2.0-2noble.20240308.201622).
14.85 ros-rolling-rmw-fastrtps-cpp set to manually installed.
14.85 The following additional packages will be installed:
14.85   acl libacl1-dev libalgorithm-c3-perl libattr1-dev libb-hooks-endofscope-perl
14.85   libb-hooks-op-check-perl libcapture-tiny-perl libclass-c3-perl
14.85   libclass-data-inheritable-perl libclass-inspector-perl
14.85   libclass-method-modifiers-perl libclass-singleton-perl libdata-optlist-perl
14.85   libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl
14.85   libdevel-callchecker-perl libdevel-stacktrace-perl
14.85   libdynaloader-functions-perl libedit2 libeval-closure-perl
14.85   libexception-class-perl libfile-sharedir-perl libhiredis1.1.0 libjson-perl
14.85   libllvm18 libmodule-implementation-perl libmodule-runtime-perl
14.85   libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl
14.85   libpackage-stash-perl libparams-classify-perl libparams-util-perl
14.85   libparams-validationcompiler-perl libperlio-gzip-perl librole-tiny-perl
14.85   libspecio-perl libsub-exporter-perl libsub-exporter-progressive-perl
14.85   libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl
14.85   libtimedate-perl libtry-tiny-perl libvariable-magic-perl libxstring-perl
14.85   lld-18 python3-wheel ros-rolling-cyclonedds ros-rolling-iceoryx-binding-c
14.85   ros-rolling-iceoryx-hoofs ros-rolling-iceoryx-posh
14.85   ros-rolling-rmw-connextdds-common ros-rolling-rti-connext-dds-cmake-module
14.85   rti-connext-dds-6.0.1
14.86 Suggested packages:
14.86   distcc | icecc libscalar-number-perl libtest-fatal-perl
14.86 Recommended packages:
14.86   libgd-gd2-perl libclass-c3-xs-perl libdevel-lexalias-perl libjson-xs-perl
14.86   libpackage-stash-xs-perl libclass-xsaccessor-perl libref-util-perl
15.05 The following NEW packages will be installed:
15.05   acl ccache lcov libacl1-dev libalgorithm-c3-perl libattr1-dev
15.05   libb-hooks-endofscope-perl libb-hooks-op-check-perl libcapture-tiny-perl
15.05   libclass-c3-perl libclass-data-inheritable-perl libclass-inspector-perl
15.05   libclass-method-modifiers-perl libclass-singleton-perl libdata-optlist-perl
15.05   libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl
15.05   libdevel-callchecker-perl libdevel-stacktrace-perl
15.05   libdynaloader-functions-perl libedit2 libeval-closure-perl
15.05   libexception-class-perl libfile-sharedir-perl libhiredis1.1.0 libjson-perl
15.05   libllvm18 libmodule-implementation-perl libmodule-runtime-perl
15.05   libmro-compat-perl libnamespace-autoclean-perl libnamespace-clean-perl
15.05   libpackage-stash-perl libparams-classify-perl libparams-util-perl
15.05   libparams-validationcompiler-perl libperlio-gzip-perl librole-tiny-perl
15.05   libspecio-perl libsub-exporter-perl libsub-exporter-progressive-perl
15.05   libsub-identify-perl libsub-install-perl libsub-name-perl libsub-quote-perl
15.05   libtimedate-perl libtry-tiny-perl libvariable-magic-perl libxstring-perl lld
15.05   lld-18 python3-pip python3-wheel ros-rolling-cyclonedds
15.05   ros-rolling-iceoryx-binding-c ros-rolling-iceoryx-hoofs
15.05   ros-rolling-iceoryx-posh ros-rolling-rmw-connextdds
15.05   ros-rolling-rmw-connextdds-common ros-rolling-rmw-cyclonedds-cpp
15.05   ros-rolling-rti-connext-dds-cmake-module rti-connext-dds-6.0.1
15.16 0 upgraded, 63 newly installed, 0 to remove and 0 not upgraded.
15.16 Need to get 191 MB of archives.
15.16 After this operation, 730 MB of additional disk space will be used.
15.16 Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 libedit2 amd64 3.1-20230828-1build1 [97.6 kB]
15.31 Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 acl amd64 2.3.2-1build1 [39.4 kB]
15.32 Get:3 http://archive.ubuntu.com/ubuntu noble/universe amd64 libhiredis1.1.0 amd64 1.2.0-6ubuntu3 [41.4 kB]
15.34 Get:4 http://archive.ubuntu.com/ubuntu noble/universe amd64 ccache amd64 4.9.1-1 [592 kB]
15.34 Get:5 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-iceoryx-binding-c amd64 2.0.5-5noble.20240309.184100 [63.7 kB]
15.43 Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 libcapture-tiny-perl all 0.48-2 [20.2 kB]
15.44 Get:7 http://archive.ubuntu.com/ubuntu noble/universe amd64 libclass-inspector-perl all 1.36-3 [15.4 kB]
15.44 Get:8 http://archive.ubuntu.com/ubuntu noble/universe amd64 libfile-sharedir-perl all 1.118-3 [14.0 kB]
15.44 Get:9 http://archive.ubuntu.com/ubuntu noble/main amd64 libb-hooks-op-check-perl amd64 0.22-3build1 [9518 B]
15.44 Get:10 http://archive.ubuntu.com/ubuntu noble/main amd64 libdynaloader-functions-perl all 0.003-3 [12.1 kB]
15.44 Get:11 http://archive.ubuntu.com/ubuntu noble/main amd64 libdevel-callchecker-perl amd64 0.008-2build3 [13.2 kB]
15.44 Get:12 http://archive.ubuntu.com/ubuntu noble/main amd64 libparams-classify-perl amd64 0.015-2build5 [20.1 kB]
15.52 Get:13 http://archive.ubuntu.com/ubuntu noble/main amd64 libmodule-runtime-perl all 0.016-2 [16.4 kB]
15.60 Get:14 http://archive.ubuntu.com/ubuntu noble/main amd64 libtry-tiny-perl all 0.31-2 [20.8 kB]
15.62 Get:15 http://archive.ubuntu.com/ubuntu noble/main amd64 libmodule-implementation-perl all 0.09-2 [12.0 kB]
15.64 Get:16 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-exporter-progressive-perl all 0.001013-3 [6718 B]
15.65 Get:17 http://archive.ubuntu.com/ubuntu noble/main amd64 libvariable-magic-perl amd64 0.63-1build3 [35.1 kB]
15.68 Get:18 http://archive.ubuntu.com/ubuntu noble/main amd64 libb-hooks-endofscope-perl all 0.28-1 [15.8 kB]
15.70 Get:19 http://archive.ubuntu.com/ubuntu noble/main amd64 libpackage-stash-perl all 0.40-1 [19.5 kB]
15.70 Get:20 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-identify-perl amd64 0.14-3build3 [9786 B]
15.70 Get:21 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-name-perl amd64 0.27-1build3 [10.8 kB]
15.70 Get:22 http://archive.ubuntu.com/ubuntu noble/main amd64 libnamespace-clean-perl all 0.27-2 [14.0 kB]
15.71 Get:23 http://archive.ubuntu.com/ubuntu noble/universe amd64 libnamespace-autoclean-perl all 0.29-2 [11.7 kB]
15.71 Get:24 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-iceoryx-hoofs amd64 2.0.5-5noble.20240309.183221 [211 kB]
15.79 Get:25 http://archive.ubuntu.com/ubuntu noble/main amd64 libparams-util-perl amd64 1.102-2build3 [21.2 kB]
15.87 Get:26 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-install-perl all 0.929-1 [9764 B]
15.87 Get:27 http://archive.ubuntu.com/ubuntu noble/main amd64 libdata-optlist-perl all 0.114-1 [9708 B]
15.88 Get:28 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-exporter-perl all 0.990-1 [49.0 kB]
15.93 Get:29 http://archive.ubuntu.com/ubuntu noble/universe amd64 libeval-closure-perl all 0.14-3 [10.1 kB]
15.93 Get:30 http://archive.ubuntu.com/ubuntu noble/main amd64 libclass-data-inheritable-perl all 0.08-3 [8084 B]
15.94 Get:31 http://archive.ubuntu.com/ubuntu noble/main amd64 libdevel-stacktrace-perl all 2.0500-1 [22.1 kB]
15.95 Get:32 http://archive.ubuntu.com/ubuntu noble/main amd64 libexception-class-perl all 1.45-1 [28.6 kB]
15.96 Get:33 http://archive.ubuntu.com/ubuntu noble/universe amd64 libparams-validationcompiler-perl all 0.31-1 [28.3 kB]
15.97 Get:34 http://archive.ubuntu.com/ubuntu noble/universe amd64 libalgorithm-c3-perl all 0.11-2 [10.2 kB]
15.97 Get:35 http://archive.ubuntu.com/ubuntu noble/universe amd64 libclass-c3-perl all 0.35-2 [18.4 kB]
16.05 Get:36 http://archive.ubuntu.com/ubuntu noble/universe amd64 libmro-compat-perl all 0.15-2 [10.1 kB]
16.08 Get:37 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-iceoryx-posh amd64 2.0.5-5noble.20240309.183814 [399 kB]
16.09 Get:38 http://archive.ubuntu.com/ubuntu noble/main amd64 libclass-method-modifiers-perl all 2.15-1 [16.1 kB]
16.11 Get:39 http://archive.ubuntu.com/ubuntu noble/main amd64 librole-tiny-perl all 2.002004-1 [16.3 kB]
16.13 Get:40 http://archive.ubuntu.com/ubuntu noble/main amd64 libsub-quote-perl all 2.006008-1ubuntu1 [20.7 kB]
16.16 Get:41 http://archive.ubuntu.com/ubuntu noble/universe amd64 libxstring-perl amd64 0.005-2build3 [7852 B]
16.16 Get:42 http://archive.ubuntu.com/ubuntu noble/universe amd64 libspecio-perl all 0.48-1 [137 kB]
16.22 Get:43 http://archive.ubuntu.com/ubuntu noble/universe amd64 libdatetime-locale-perl all 1:1.37-1 [2833 kB]
16.38 Get:44 http://archive.ubuntu.com/ubuntu noble/universe amd64 libclass-singleton-perl all 1.6-2 [11.5 kB]
16.38 Get:45 http://archive.ubuntu.com/ubuntu noble/universe amd64 libdatetime-timezone-perl all 1:2.62-1+2024a [262 kB]
16.38 Get:46 http://archive.ubuntu.com/ubuntu noble/universe amd64 libdatetime-perl amd64 2:1.65-1build2 [95.8 kB]
16.38 Get:47 http://archive.ubuntu.com/ubuntu noble/main amd64 libtimedate-perl all 2.3300-2 [34.0 kB]
16.46 Get:48 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-cyclonedds amd64 0.10.4-3noble.20240309.184514 [1035 kB]
16.48 Get:49 http://archive.ubuntu.com/ubuntu noble/main amd64 libjson-perl all 4.10000-1 [81.9 kB]
16.65 Get:50 http://archive.ubuntu.com/ubuntu noble/main amd64 libperlio-gzip-perl amd64 0.20-1build4 [14.6 kB]
16.66 Get:51 http://archive.ubuntu.com/ubuntu noble/universe amd64 lcov all 2.0-4ubuntu2 [223 kB]
16.75 Get:52 http://archive.ubuntu.com/ubuntu noble/main amd64 libllvm18 amd64 1:18.1.2-1ubuntu3 [27.5 MB]
16.84 Get:53 http://packages.ros.org/ros2/ubuntu noble/main amd64 rti-connext-dds-6.0.1 amd64 6.0.1.25-1 [154 MB]
17.71 Get:54 http://archive.ubuntu.com/ubuntu noble/universe amd64 lld-18 amd64 1:18.1.2-1ubuntu3 [1375 kB]
17.75 Get:55 http://archive.ubuntu.com/ubuntu noble/universe amd64 lld amd64 1:18.0-59~exp2 [5494 B]
17.75 Get:56 http://archive.ubuntu.com/ubuntu noble/universe amd64 python3-wheel all 0.42.0-2 [53.1 kB]
17.76 Get:57 http://archive.ubuntu.com/ubuntu noble/universe amd64 python3-pip all 24.0+dfsg-1ubuntu1 [1316 kB]
17.80 Get:58 http://archive.ubuntu.com/ubuntu noble/main amd64 libattr1-dev amd64 1:2.5.2-1build1 [23.0 kB]
17.80 Get:59 http://archive.ubuntu.com/ubuntu noble/main amd64 libacl1-dev amd64 2.3.2-1build1 [78.5 kB]
68.48 Get:60 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-rti-connext-dds-cmake-module amd64 0.20.1-1noble.20240309.183205 [12.2 kB]
68.48 Get:61 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-rmw-connextdds-common amd64 0.20.1-1noble.20240309.183641 [258 kB]
68.48 Get:62 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-rmw-connextdds amd64 0.20.1-1noble.20240309.183803 [16.5 kB]
68.48 Get:63 http://packages.ros.org/ros2/ubuntu noble/main amd64 ros-rolling-rmw-cyclonedds-cpp amd64 2.1.0-2noble.20240309.184728 [174 kB]
68.65 debconf: delaying package configuration, since apt-utils is not installed
68.68 Fetched 191 MB in 53s (3576 kB/s)
68.70 Selecting previously unselected package libedit2:amd64.
(Reading database ... 39191 files and directories currently installed.)
68.72 Preparing to unpack .../00-libedit2_3.1-20230828-1build1_amd64.deb ...
68.72 Unpacking libedit2:amd64 (3.1-20230828-1build1) ...
68.74 Selecting previously unselected package acl.
68.74 Preparing to unpack .../01-acl_2.3.2-1build1_amd64.deb ...
68.74 Unpacking acl (2.3.2-1build1) ...
68.76 Selecting previously unselected package libhiredis1.1.0:amd64.
68.77 Preparing to unpack .../02-libhiredis1.1.0_1.2.0-6ubuntu3_amd64.deb ...
68.77 Unpacking libhiredis1.1.0:amd64 (1.2.0-6ubuntu3) ...
68.79 Selecting previously unselected package ccache.
68.79 Preparing to unpack .../03-ccache_4.9.1-1_amd64.deb ...
68.79 Unpacking ccache (4.9.1-1) ...
68.81 Selecting previously unselected package libcapture-tiny-perl.
68.82 Preparing to unpack .../04-libcapture-tiny-perl_0.48-2_all.deb ...
68.82 Unpacking libcapture-tiny-perl (0.48-2) ...
68.83 Selecting previously unselected package libclass-inspector-perl.
68.84 Preparing to unpack .../05-libclass-inspector-perl_1.36-3_all.deb ...
68.84 Unpacking libclass-inspector-perl (1.36-3) ...
68.85 Selecting previously unselected package libfile-sharedir-perl.
68.86 Preparing to unpack .../06-libfile-sharedir-perl_1.118-3_all.deb ...
68.86 Unpacking libfile-sharedir-perl (1.118-3) ...
68.87 Selecting previously unselected package libb-hooks-op-check-perl:amd64.
68.88 Preparing to unpack .../07-libb-hooks-op-check-perl_0.22-3build1_amd64.deb ...
68.88 Unpacking libb-hooks-op-check-perl:amd64 (0.22-3build1) ...
68.90 Selecting previously unselected package libdynaloader-functions-perl.
68.90 Preparing to unpack .../08-libdynaloader-functions-perl_0.003-3_all.deb ...
68.90 Unpacking libdynaloader-functions-perl (0.003-3) ...
68.92 Selecting previously unselected package libdevel-callchecker-perl:amd64.
68.92 Preparing to unpack .../09-libdevel-callchecker-perl_0.008-2build3_amd64.deb ...
68.92 Unpacking libdevel-callchecker-perl:amd64 (0.008-2build3) ...
68.94 Selecting previously unselected package libparams-classify-perl:amd64.
68.94 Preparing to unpack .../10-libparams-classify-perl_0.015-2build5_amd64.deb ...
68.94 Unpacking libparams-classify-perl:amd64 (0.015-2build5) ...
68.96 Selecting previously unselected package libmodule-runtime-perl.
68.96 Preparing to unpack .../11-libmodule-runtime-perl_0.016-2_all.deb ...
68.97 Unpacking libmodule-runtime-perl (0.016-2) ...
68.98 Selecting previously unselected package libtry-tiny-perl.
68.98 Preparing to unpack .../12-libtry-tiny-perl_0.31-2_all.deb ...
68.99 Unpacking libtry-tiny-perl (0.31-2) ...
69.00 Selecting previously unselected package libmodule-implementation-perl.
69.01 Preparing to unpack .../13-libmodule-implementation-perl_0.09-2_all.deb ...
69.01 Unpacking libmodule-implementation-perl (0.09-2) ...
69.02 Selecting previously unselected package libsub-exporter-progressive-perl.
69.03 Preparing to unpack .../14-libsub-exporter-progressive-perl_0.001013-3_all.deb ...
69.03 Unpacking libsub-exporter-progressive-perl (0.001013-3) ...
69.05 Selecting previously unselected package libvariable-magic-perl.
69.05 Preparing to unpack .../15-libvariable-magic-perl_0.63-1build3_amd64.deb ...
69.05 Unpacking libvariable-magic-perl (0.63-1build3) ...
69.07 Selecting previously unselected package libb-hooks-endofscope-perl.
69.07 Preparing to unpack .../16-libb-hooks-endofscope-perl_0.28-1_all.deb ...
69.08 Unpacking libb-hooks-endofscope-perl (0.28-1) ...
69.09 Selecting previously unselected package libpackage-stash-perl.
69.09 Preparing to unpack .../17-libpackage-stash-perl_0.40-1_all.deb ...
69.10 Unpacking libpackage-stash-perl (0.40-1) ...
69.11 Selecting previously unselected package libsub-identify-perl.
69.12 Preparing to unpack .../18-libsub-identify-perl_0.14-3build3_amd64.deb ...
69.12 Unpacking libsub-identify-perl (0.14-3build3) ...
69.13 Selecting previously unselected package libsub-name-perl:amd64.
69.14 Preparing to unpack .../19-libsub-name-perl_0.27-1build3_amd64.deb ...
69.14 Unpacking libsub-name-perl:amd64 (0.27-1build3) ...
69.16 Selecting previously unselected package libnamespace-clean-perl.
69.16 Preparing to unpack .../20-libnamespace-clean-perl_0.27-2_all.deb ...
69.16 Unpacking libnamespace-clean-perl (0.27-2) ...
69.18 Selecting previously unselected package libnamespace-autoclean-perl.
69.18 Preparing to unpack .../21-libnamespace-autoclean-perl_0.29-2_all.deb ...
69.18 Unpacking libnamespace-autoclean-perl (0.29-2) ...
69.20 Selecting previously unselected package libparams-util-perl.
69.20 Preparing to unpack .../22-libparams-util-perl_1.102-2build3_amd64.deb ...
69.20 Unpacking libparams-util-perl (1.102-2build3) ...
69.22 Selecting previously unselected package libsub-install-perl.
69.22 Preparing to unpack .../23-libsub-install-perl_0.929-1_all.deb ...
69.22 Unpacking libsub-install-perl (0.929-1) ...
69.24 Selecting previously unselected package libdata-optlist-perl.
69.24 Preparing to unpack .../24-libdata-optlist-perl_0.114-1_all.deb ...
69.24 Unpacking libdata-optlist-perl (0.114-1) ...
69.26 Selecting previously unselected package libsub-exporter-perl.
69.26 Preparing to unpack .../25-libsub-exporter-perl_0.990-1_all.deb ...
69.26 Unpacking libsub-exporter-perl (0.990-1) ...
69.28 Selecting previously unselected package libeval-closure-perl.
69.28 Preparing to unpack .../26-libeval-closure-perl_0.14-3_all.deb ...
69.29 Unpacking libeval-closure-perl (0.14-3) ...
69.30 Selecting previously unselected package libclass-data-inheritable-perl.
69.30 Preparing to unpack .../27-libclass-data-inheritable-perl_0.08-3_all.deb ...
69.31 Unpacking libclass-data-inheritable-perl (0.08-3) ...
69.32 Selecting previously unselected package libdevel-stacktrace-perl.
69.33 Preparing to unpack .../28-libdevel-stacktrace-perl_2.0500-1_all.deb ...
69.33 Unpacking libdevel-stacktrace-perl (2.0500-1) ...
69.34 Selecting previously unselected package libexception-class-perl.
69.35 Preparing to unpack .../29-libexception-class-perl_1.45-1_all.deb ...
69.35 Unpacking libexception-class-perl (1.45-1) ...
69.37 Selecting previously unselected package libparams-validationcompiler-perl.
69.37 Preparing to unpack .../30-libparams-validationcompiler-perl_0.31-1_all.deb ...
69.37 Unpacking libparams-validationcompiler-perl (0.31-1) ...
69.39 Selecting previously unselected package libalgorithm-c3-perl.
69.39 Preparing to unpack .../31-libalgorithm-c3-perl_0.11-2_all.deb ...
69.39 Unpacking libalgorithm-c3-perl (0.11-2) ...
69.41 Selecting previously unselected package libclass-c3-perl.
69.41 Preparing to unpack .../32-libclass-c3-perl_0.35-2_all.deb ...
69.41 Unpacking libclass-c3-perl (0.35-2) ...
69.43 Selecting previously unselected package libmro-compat-perl.
69.43 Preparing to unpack .../33-libmro-compat-perl_0.15-2_all.deb ...
69.43 Unpacking libmro-compat-perl (0.15-2) ...
69.45 Selecting previously unselected package libclass-method-modifiers-perl.
69.45 Preparing to unpack .../34-libclass-method-modifiers-perl_2.15-1_all.deb ...
69.45 Unpacking libclass-method-modifiers-perl (2.15-1) ...
69.47 Selecting previously unselected package librole-tiny-perl.
69.47 Preparing to unpack .../35-librole-tiny-perl_2.002004-1_all.deb ...
69.47 Unpacking librole-tiny-perl (2.002004-1) ...
69.49 Selecting previously unselected package libsub-quote-perl.
69.49 Preparing to unpack .../36-libsub-quote-perl_2.006008-1ubuntu1_all.deb ...
69.49 Unpacking libsub-quote-perl (2.006008-1ubuntu1) ...
69.51 Selecting previously unselected package libxstring-perl:amd64.
69.51 Preparing to unpack .../37-libxstring-perl_0.005-2build3_amd64.deb ...
69.51 Unpacking libxstring-perl:amd64 (0.005-2build3) ...
69.53 Selecting previously unselected package libspecio-perl.
69.53 Preparing to unpack .../38-libspecio-perl_0.48-1_all.deb ...
69.53 Unpacking libspecio-perl (0.48-1) ...
69.56 Selecting previously unselected package libdatetime-locale-perl.
69.56 Preparing to unpack .../39-libdatetime-locale-perl_1%3a1.37-1_all.deb ...
69.56 Unpacking libdatetime-locale-perl (1:1.37-1) ...
69.88 Selecting previously unselected package libclass-singleton-perl.
69.89 Preparing to unpack .../40-libclass-singleton-perl_1.6-2_all.deb ...
69.89 Unpacking libclass-singleton-perl (1.6-2) ...
69.91 Selecting previously unselected package libdatetime-timezone-perl.
69.91 Preparing to unpack .../41-libdatetime-timezone-perl_1%3a2.62-1+2024a_all.deb ...
69.91 Unpacking libdatetime-timezone-perl (1:2.62-1+2024a) ...
70.00 Selecting previously unselected package libdatetime-perl.
70.01 Preparing to unpack .../42-libdatetime-perl_2%3a1.65-1build2_amd64.deb ...
70.01 Unpacking libdatetime-perl (2:1.65-1build2) ...
70.03 Selecting previously unselected package libtimedate-perl.
70.03 Preparing to unpack .../43-libtimedate-perl_2.3300-2_all.deb ...
70.04 Unpacking libtimedate-perl (2.3300-2) ...
70.06 Selecting previously unselected package libjson-perl.
70.06 Preparing to unpack .../44-libjson-perl_4.10000-1_all.deb ...
70.06 Unpacking libjson-perl (4.10000-1) ...
70.08 Selecting previously unselected package libperlio-gzip-perl.
70.09 Preparing to unpack .../45-libperlio-gzip-perl_0.20-1build4_amd64.deb ...
70.09 Unpacking libperlio-gzip-perl (0.20-1build4) ...
70.11 Selecting previously unselected package lcov.
70.11 Preparing to unpack .../46-lcov_2.0-4ubuntu2_all.deb ...
70.11 Unpacking lcov (2.0-4ubuntu2) ...
70.14 Selecting previously unselected package libllvm18:amd64.
70.14 Preparing to unpack .../47-libllvm18_1%3a18.1.2-1ubuntu3_amd64.deb ...
70.14 Unpacking libllvm18:amd64 (1:18.1.2-1ubuntu3) ...
70.61 Selecting previously unselected package lld-18.
70.61 Preparing to unpack .../48-lld-18_1%3a18.1.2-1ubuntu3_amd64.deb ...
70.61 Unpacking lld-18 (1:18.1.2-1ubuntu3) ...
70.65 Selecting previously unselected package lld:amd64.
70.65 Preparing to unpack .../49-lld_1%3a18.0-59~exp2_amd64.deb ...
70.65 Unpacking lld:amd64 (1:18.0-59~exp2) ...
70.67 Selecting previously unselected package python3-wheel.
70.67 Preparing to unpack .../50-python3-wheel_0.42.0-2_all.deb ...
70.67 Unpacking python3-wheel (0.42.0-2) ...
70.70 Selecting previously unselected package python3-pip.
70.70 Preparing to unpack .../51-python3-pip_24.0+dfsg-1ubuntu1_all.deb ...
70.70 Unpacking python3-pip (24.0+dfsg-1ubuntu1) ...
70.78 Selecting previously unselected package ros-rolling-iceoryx-binding-c.
70.78 Preparing to unpack .../52-ros-rolling-iceoryx-binding-c_2.0.5-5noble.20240309.184100_amd64.deb ...
70.79 Unpacking ros-rolling-iceoryx-binding-c (2.0.5-5noble.20240309.184100) ...
70.82 Selecting previously unselected package libattr1-dev:amd64.
70.82 Preparing to unpack .../53-libattr1-dev_1%3a2.5.2-1build1_amd64.deb ...
70.82 Unpacking libattr1-dev:amd64 (1:2.5.2-1build1) ...
70.84 Selecting previously unselected package libacl1-dev:amd64.
70.85 Preparing to unpack .../54-libacl1-dev_2.3.2-1build1_amd64.deb ...
70.85 Unpacking libacl1-dev:amd64 (2.3.2-1build1) ...
70.87 Selecting previously unselected package ros-rolling-iceoryx-hoofs.
70.87 Preparing to unpack .../55-ros-rolling-iceoryx-hoofs_2.0.5-5noble.20240309.183221_amd64.deb ...
70.88 Unpacking ros-rolling-iceoryx-hoofs (2.0.5-5noble.20240309.183221) ...
70.93 Selecting previously unselected package ros-rolling-iceoryx-posh.
70.93 Preparing to unpack .../56-ros-rolling-iceoryx-posh_2.0.5-5noble.20240309.183814_amd64.deb ...
70.93 Unpacking ros-rolling-iceoryx-posh (2.0.5-5noble.20240309.183814) ...
71.00 Selecting previously unselected package ros-rolling-cyclonedds.
71.00 Preparing to unpack .../57-ros-rolling-cyclonedds_0.10.4-3noble.20240309.184514_amd64.deb ...
71.00 Unpacking ros-rolling-cyclonedds (0.10.4-3noble.20240309.184514) ...
71.07 Selecting previously unselected package rti-connext-dds-6.0.1.
71.07 Preparing to unpack .../58-rti-connext-dds-6.0.1_6.0.1.25-1_amd64.deb ...
71.12 config: RTI license agreement for non-commercial and pre-commercial user already accepted in shell environment.
71.12 rti-connext-dds-6.0.1: RTI license agreement for non-commercial and pre-commercial use accepted.
71.13 Unpacking rti-connext-dds-6.0.1 (6.0.1.25-1) ...
73.86 Selecting previously unselected package ros-rolling-rti-connext-dds-cmake-module.
73.87 Preparing to unpack .../59-ros-rolling-rti-connext-dds-cmake-module_0.20.1-1noble.20240309.183205_amd64.deb ...
73.87 Unpacking ros-rolling-rti-connext-dds-cmake-module (0.20.1-1noble.20240309.183205) ...
73.89 Selecting previously unselected package ros-rolling-rmw-connextdds-common.
73.89 Preparing to unpack .../60-ros-rolling-rmw-connextdds-common_0.20.1-1noble.20240309.183641_amd64.deb ...
73.90 Unpacking ros-rolling-rmw-connextdds-common (0.20.1-1noble.20240309.183641) ...
73.92 Selecting previously unselected package ros-rolling-rmw-connextdds.
73.93 Preparing to unpack .../61-ros-rolling-rmw-connextdds_0.20.1-1noble.20240309.183803_amd64.deb ...
73.93 Unpacking ros-rolling-rmw-connextdds (0.20.1-1noble.20240309.183803) ...
73.95 Selecting previously unselected package ros-rolling-rmw-cyclonedds-cpp.
73.95 Preparing to unpack .../62-ros-rolling-rmw-cyclonedds-cpp_2.1.0-2noble.20240309.184728_amd64.deb ...
73.95 Unpacking ros-rolling-rmw-cyclonedds-cpp (2.1.0-2noble.20240309.184728) ...
73.99 Setting up libattr1-dev:amd64 (1:2.5.2-1build1) ...
73.99 Setting up libclass-inspector-perl (1.36-3) ...
74.00 Setting up libdynaloader-functions-perl (0.003-3) ...
74.00 Setting up libclass-method-modifiers-perl (2.15-1) ...
74.00 Setting up libsub-identify-perl (0.14-3build3) ...
74.01 Setting up rti-connext-dds-6.0.1 (6.0.1.25-1) ...
74.01 Setting up libedit2:amd64 (3.1-20230828-1build1) ...
74.02 Setting up libtry-tiny-perl (0.31-2) ...
74.02 Setting up libclass-singleton-perl (1.6-2) ...
74.02 Setting up libxstring-perl:amd64 (0.005-2build3) ...
74.03 Setting up python3-wheel (0.42.0-2) ...
74.18 Setting up libsub-install-perl (0.929-1) ...
74.18 Setting up acl (2.3.2-1build1) ...
74.19 Setting up libclass-data-inheritable-perl (0.08-3) ...
74.19 Setting up libalgorithm-c3-perl (0.11-2) ...
74.20 Setting up libvariable-magic-perl (0.63-1build3) ...
74.20 Setting up libb-hooks-op-check-perl:amd64 (0.22-3build1) ...
74.20 Setting up python3-pip (24.0+dfsg-1ubuntu1) ...
75.29 Setting up libparams-util-perl (1.102-2build3) ...
75.30 Setting up libsub-exporter-progressive-perl (0.001013-3) ...
75.30 Setting up libcapture-tiny-perl (0.48-2) ...
75.30 Setting up libtimedate-perl (2.3300-2) ...
75.31 Setting up libsub-name-perl:amd64 (0.27-1build3) ...
75.31 Setting up libjson-perl (4.10000-1) ...
75.31 Setting up librole-tiny-perl (2.002004-1) ...
75.32 Setting up libfile-sharedir-perl (1.118-3) ...
75.32 Setting up libsub-quote-perl (2.006008-1ubuntu1) ...
75.32 Setting up libdevel-stacktrace-perl (2.0500-1) ...
75.33 Setting up ros-rolling-iceoryx-binding-c (2.0.5-5noble.20240309.184100) ...
75.33 Setting up libperlio-gzip-perl (0.20-1build4) ...
75.34 Setting up libhiredis1.1.0:amd64 (1.2.0-6ubuntu3) ...
75.34 Setting up libllvm18:amd64 (1:18.1.2-1ubuntu3) ...
75.34 Setting up libacl1-dev:amd64 (2.3.2-1build1) ...
75.35 Setting up ros-rolling-rti-connext-dds-cmake-module (0.20.1-1noble.20240309.183205) ...
75.35 Setting up ccache (4.9.1-1) ...
75.35 Updating symlinks in /usr/lib/ccache ...
75.36 Setting up ros-rolling-iceoryx-hoofs (2.0.5-5noble.20240309.183221) ...
75.36 Setting up libexception-class-perl (1.45-1) ...
75.37 Setting up libclass-c3-perl (0.35-2) ...
75.37 Setting up libdevel-callchecker-perl:amd64 (0.008-2build3) ...
75.38 Setting up libdata-optlist-perl (0.114-1) ...
75.38 Setting up ros-rolling-rmw-connextdds-common (0.20.1-1noble.20240309.183641) ...
75.38 Setting up libmro-compat-perl (0.15-2) ...
75.39 Setting up libsub-exporter-perl (0.990-1) ...
75.39 Setting up ros-rolling-iceoryx-posh (2.0.5-5noble.20240309.183814) ...
75.39 Setting up lld-18 (1:18.1.2-1ubuntu3) ...
75.40 Setting up libeval-closure-perl (0.14-3) ...
75.40 Setting up libparams-validationcompiler-perl (0.31-1) ...
75.41 Setting up lld:amd64 (1:18.0-59~exp2) ...
75.41 Setting up libparams-classify-perl:amd64 (0.015-2build5) ...
75.41 Setting up ros-rolling-rmw-connextdds (0.20.1-1noble.20240309.183803) ...
75.42 Setting up ros-rolling-cyclonedds (0.10.4-3noble.20240309.184514) ...
75.42 Setting up libmodule-runtime-perl (0.016-2) ...
75.43 Setting up ros-rolling-rmw-cyclonedds-cpp (2.1.0-2noble.20240309.184728) ...
75.43 Setting up libmodule-implementation-perl (0.09-2) ...
75.43 Setting up libpackage-stash-perl (0.40-1) ...
75.44 Setting up libspecio-perl (0.48-1) ...
75.44 Setting up libb-hooks-endofscope-perl (0.28-1) ...
75.44 Setting up libnamespace-clean-perl (0.27-2) ...
75.45 Setting up libnamespace-autoclean-perl (0.29-2) ...
75.45 Setting up libdatetime-locale-perl (1:1.37-1) ...
75.46 Setting up libdatetime-timezone-perl (1:2.62-1+2024a) ...
75.46 Setting up libdatetime-perl (2:1.65-1build2) ...
75.46 Setting up lcov (2.0-4ubuntu2) ...
75.47 Processing triggers for libc-bin (2.39-0ubuntu8) ...
75.93 error: externally-managed-environment
75.93 
75.93 × This environment is externally managed
75.93 ╰─> To install Python packages system-wide, try apt install
75.93     python3-xyz, where xyz is the package you are trying to
75.93     install.
75.93     
75.93     If you wish to install a non-Debian-packaged Python package,
75.93     create a virtual environment using python3 -m venv path/to/venv.
75.93     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
75.93     sure you have python3-full installed.
75.93     
75.93     If you wish to install a non-Debian packaged Python application,
75.93     it may be easiest to use pipx install xyz, which will manage a
75.93     virtual environment for you. Make sure you have pipx installed.
75.93     
75.93     See /usr/share/doc/python3.12/README.venv for more information.
75.93 
75.93 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
75.93 hint: See PEP 668 for the detailed specification.
------
Dockerfile:50
--------------------
  49 |     ARG RTI_NC_LICENSE_ACCEPTED=yes
  50 | >>> RUN apt-get update && \
  51 | >>>     apt-get upgrade -y --with-new-pkgs && \
  52 | >>>     apt-get install -y \
  53 | >>>       ccache \
  54 | >>>       lcov \
  55 | >>>       lld \
  56 | >>>       python3-pip \
  57 | >>>       ros-$ROS_DISTRO-rmw-fastrtps-cpp \
  58 | >>>       ros-$ROS_DISTRO-rmw-connextdds \
  59 | >>>       ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
  60 | >>>     && pip3 install \
  61 | >>>       fastcov \
  62 | >>>       git+https://github.com/ruffsl/colcon-cache.git@a937541bfc496c7a267db7ee9d6cceca61e470ca \
  63 | >>>       git+https://github.com/ruffsl/colcon-clean.git@a7f1074d1ebc1a54a6508625b117974f2672f2a9 \
  64 | >>>     && rosdep update \
  65 | >>>     && colcon mixin update \
  66 | >>>     && colcon metadata update \
  67 | >>>     && rm -rf /var/lib/apt/lists/*
  68 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get upgrade -y --with-new-pkgs &&     apt-get install -y       ccache       lcov       lld       python3-pip       ros-$ROS_DISTRO-rmw-fastrtps-cpp       ros-$ROS_DISTRO-rmw-connextdds       ros-$ROS_DISTRO-rmw-cyclonedds-cpp     && pip3 install       fastcov       git+https://github.com/ruffsl/colcon-cache.git@a937541bfc496c7a267db7ee9d6cceca61e470ca       git+https://github.com/ruffsl/colcon-clean.git@a7f1074d1ebc1a54a6508625b117974f2672f2a9     && rosdep update     && colcon mixin update     && colcon metadata update     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1
 ✘  ~/nav2_work  
 ✘  ~/nav2_work  docker build --tag navigation2:$ROS_DISTRO \ 
  --build-arg FROM_IMAGE=ros:$ROS_DISTRO \
  --build-arg OVERLAY_MIXINS="release ccache lld" \
  --cache-from ghcr.io/ros-planning/navigation2:main \
  ./navigation2

```
#### Additional information
* This behavior happens in main also

----

**Comment by Ayush1285** [comment]
Hi @stevedanomodolor, I'm also facing the same issue on the main branch. How did you resolve it?

**Comment by stevedanomodolor** [comment]
I merged with latest main and made sure I had the latest dockers

**Comment by andywot** [comment]
@Ayush1285 @stevedanomodolor Hi, I had the latest docker and latest commit on main but I still have this issue. Any idea on how to solve it?

**Comment by Ayush1285** [comment]
> @Ayush1285 @stevedanomodolor Hi, I had the latest docker and latest commit on main but I still have this issue. Any idea on how to solve it?

Can you please check version of Ubuntu in your docker  env? Currently due to migration of ROS Rolling from 22.04 to 24.04, we are facing issues regarding packages not available in rosdep. You can try building your own docker image of Nav2 main branch from the ROS Jazzy image, and see if it works or not.

**Comment by stevedanomodolor** [comment]
root@stevedan:/opt/overlay_ws# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
ARG FROM_IMAGE=ros:rolling
ARG UNDERLAY_WS=/opt/underlay_ws
ARG OVERLAY_WS=/opt/overlay_ws
